#!/usr/bin/env python3
"""Zero-setup WinCreator path for one claim and one gate.

Usage:
    python3 quick_prove.py "claim in plain language" -- command arg ...

The command creates a minimal private WinCreator ledger under .wincreator/,
binds the plain-language claim to the exact gate, captures the run, and in
Lite mode automatically records the mechanical review. Standard keeps the
same one-line entry point but stops at PENDING for separate review.
"""

import argparse
from datetime import datetime, timezone
import os
from pathlib import Path
import shlex
import sys
import uuid

import wincreator


DEFAULT_QUICK_LEDGER = os.path.join(".wincreator", "PROOF_LEDGER.md")


def _new_claim_id():
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    return f"Q-{stamp}-{uuid.uuid4().hex[:8]}"


def _ledger_header():
    return (
        "# WinCreator quick proofs\n\n"
        "This ledger is generated by `quick_prove.py`. Keep it if the proof "
        "must remain auditable; delete the whole `.wincreator/` directory if "
        "the proof was disposable.\n\n"
        "| ID | Level | Claim | Gate (what proves it) | Status | Evidence |\n"
        "|----|-------|-------|------------------------|--------|----------|\n"
    )


def ensure_claim(ledger_path, claim_id, claim_text, command):
    ledger_path = os.path.abspath(ledger_path)
    Path(ledger_path).parent.mkdir(parents=True, exist_ok=True)
    gate = shlex.join(command)
    row = (
        "| "
        + " | ".join(
            wincreator.escape_cell(value)
            for value in (claim_id, "Micro", claim_text, f"`{gate}`", "CLAIMED", "")
        )
        + " |\n"
    )
    with wincreator._file_lock(ledger_path):
        path = Path(ledger_path)
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            if existing and not existing.endswith("\n"):
                existing += "\n"
        else:
            existing = _ledger_header()
        mode = (os.stat(ledger_path).st_mode & 0o777) if os.path.exists(ledger_path) else 0o600
        wincreator._atomic_write(ledger_path, (existing + row).encode("utf-8"), mode)
    return ledger_path


def build_parser():
    parser = argparse.ArgumentParser(
        prog="wincreator-quick",
        description="Prove one explicit claim with one real command, with no ledger setup.",
    )
    parser.add_argument("claim", help="the exact thing the command is supposed to prove")
    parser.add_argument("--tier", choices=("lite", "standard"), default="lite")
    parser.add_argument("--builder")
    parser.add_argument("--ledger", default=DEFAULT_QUICK_LEDGER)
    parser.add_argument("--attest-dir", default=wincreator.DEFAULT_ATTEST_DIR)
    parser.add_argument("--timeout", type=float)
    parser.add_argument("--file", action="append", default=[])
    parser.add_argument("--optional-file", action="append", default=[])
    parser.add_argument("--redact", action="append", default=[])
    parser.add_argument("--redact-regex", action="append", default=[])
    parser.add_argument("--max-output-bytes", type=int, default=wincreator.DEFAULT_MAX_OUTPUT_BYTES)
    parser.add_argument("--no-output-body", action="store_true")
    parser.add_argument("--private", action="store_true")
    parser.add_argument("gate", nargs=argparse.REMAINDER)
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    command = list(args.gate)
    if command and command[0] == "--":
        command = command[1:]
    if not command:
        print("ERROR: supply the real gate after `--`", file=sys.stderr)
        return 2

    claim_id = _new_claim_id()
    try:
        ledger = ensure_claim(args.ledger, claim_id, args.claim, command)
        attestation, path, code = wincreator.run_and_attest(
            claim_id,
            command,
            ledger=ledger,
            files=args.file,
            optional_files=args.optional_file,
            attest_dir=args.attest_dir,
            timeout=args.timeout,
            tier=args.tier,
            builder=args.builder,
            auto_approve_lite=(args.tier == "lite"),
            redact=args.redact,
            redact_regex=args.redact_regex,
            max_output_bytes=args.max_output_bytes,
            no_output_body=args.no_output_body,
            private=args.private,
        )
    except (OSError, ValueError, KeyError, RuntimeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2

    capture = attestation["payload"]["capture"]
    status = wincreator.read_claim(ledger, claim_id)["status"]
    print(f"[{status}] {args.claim}")
    print(f"[CLAIM] {claim_id}")
    print(f"[GATE] {shlex.join(command)}")
    print(f"[CAPTURE] {capture['status']} exit={capture['exit_code']}")
    print(f"[ATTESTATION] {path} sha256={attestation['digest']['value']}")
    print(f"[LEDGER] {ledger}")
    if args.tier == "standard" and capture["status"] == "CAPTURED_PASS":
        print("[NEXT] independent review required before EVIDENCED")
    return code


if __name__ == "__main__":
    sys.exit(main())
